
'use strict';
const $=id=>document.getElementById(id), video=$('video');
const state={source:null,url:null,ready:false,busy:false,cancel:false,shots:[],nextId:1,previewId:null,previewURL:null,previewSeq:0,loadSeq:0,undo:[],dirty:false,scrubbing:false,workspace:'video',functionId:'manual',sourceFile:null,audioExporting:false,audioCancel:false};
video.muted=false;video.volume=.8;
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').hidden=true,4500)}
function timeText(seconds){const ms=Math.round(Math.max(0,seconds)*1000),h=Math.floor(ms/3600000),m=Math.floor(ms/60000)%60,s=Math.floor(ms/1000)%60;return [h,m,s].map(v=>String(v).padStart(2,'0')).join(':')+'.'+String(ms%1000).padStart(3,'0')}
function fps(){const v=Number($('fps').value);if(!Number.isFinite(v)||v<1||v>240)throw Error('步进帧率须在 1–240 之间');return v}
function settings(){return {frameRate:Number($('fps').value),color:$('stampColor').value,watermark:$('watermark').checked,mode:$('stampMode').value,position:$('stampPosition').value,size:Number($('stampSize').value)/100,start:$('recordStart').value,format:$('format').value,quality:Number($('quality').value)/100,caseName:$('caseName').value.trim(),prefix:$('prefix').value.trim()||'视频截图',sort:$('sort').value}}
function hasMark(shot,s=settings()){return shot.watermark==='on'||(shot.watermark==='inherit'&&s.watermark)}
function stamp(t,s=settings(),strict=false){if(s.mode==='elapsed')return '视频时间 '+timeText(t);const date=new Date(s.start);if(!s.start||!Number.isFinite(date.getTime())){if(strict)throw Error('请填写有效的录像起始时间，或改为「视频内时间」');return '请填写录像起始时间'}const d=new Date(date.getTime()+Math.round(t*1000));return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')} ${[d.getHours(),d.getMinutes(),d.getSeconds()].map(v=>String(v).padStart(2,'0')).join(':')}.${String(d.getMilliseconds()).padStart(3,'0')}`}
function markStyle(el,s){el.style.top=s.position[0]==='t'?'7px':'auto';el.style.bottom=s.position[0]==='b'?'7px':'auto';el.style.left=s.position[1]==='l'?'7px':'auto';el.style.right=s.position[1]==='r'?'7px':'auto'}
let liveMarkStyle='',timeSyncFrame=0;
function syncTime(){
 const t=video.currentTime||0,s=settings(),now=timeText(t),mark=$('screenMark');
 if($('now').textContent!==now)$('now').textContent=now;
 if(!video.seeking&&!state.scrubbing&&Number($('timeline').value)!==t)$('timeline').value=t;
 const text=stamp(t,s);if(mark.textContent!==text)mark.textContent=text;
 const hidden=!state.ready||!s.watermark;if(mark.hidden!==hidden)mark.hidden=hidden;
 const style=s.position+'|'+s.color;if(style!==liveMarkStyle){markStyle(mark,s);mark.style.color=s.color;liveMarkStyle=style}
}
function queueTimeSync(){if(!timeSyncFrame)timeSyncFrame=requestAnimationFrame(()=>{timeSyncFrame=0;syncTime()})}
function updateControls(){for(const id of ['playBtn','prevBtn','nextBtn','captureBtn','jumpBtn','timeline','setStart','setEnd','batchBtn'])$(id).disabled=!state.ready||state.busy;for(const id of ['openBtn','pickBtn','fileInput','speed','fps','batchMode','batchStart','batchEnd','batchStep'])$(id).disabled=state.busy;const any=state.shots.length>0;for(const id of ['csvBtn','zipBtn','clearBtn','selectAll'])$(id).disabled=!any||state.busy;const selected=state.shots.filter(s=>s.selected).length;const kept=state.shots.filter(s=>s.decision!=='exclude').length;$('reviewCounts').textContent=`保留 ${kept} · 排除 ${state.shots.length-kept}`;$('saveProjectBtn').disabled=!any||state.busy;$('restoreProjectBtn').disabled=state.busy;$('undoBtn').disabled=!state.undo.length||state.busy;$('csvBtn').disabled=!shotsForExport().length||state.busy;$('zipBtn').disabled=!shotsForExport().length||state.busy;$('exportHint').textContent=selected?`导出所选 ${shotsForExport().length} 张保留截图`:`导出全部 ${kept} 张保留截图`;$('deleteSelected').disabled=!selected||state.busy;$('selectAll').disabled=!kept||state.busy||$('reviewFilter').value==='exclude';estimateBatch();$('count').textContent=state.shots.length;$('selectedCount').textContent='已选 '+selected+' 张';$('selectAll').checked=kept>0&&selected===kept;$('selectAll').indeterminate=selected>0&&selected<kept;$('cancelBtn').hidden=!state.busy||!state.batching;$('playBtn').textContent=video.paused?'▶ 播放':'❚❚ 暂停';updateAudioControls()}
async function loadFile(file){if(state.busy)return;if(!file)return;const seq=++state.loadSeq;video.pause();state.ready=false;state.scrubbing=false;updateControls();state.sourceFile=file;if(state.url)URL.revokeObjectURL(state.url);state.url=URL.createObjectURL(file);state.source={name:fileName(file.name),extension:getExtension(file.name),size:file.size,lastModified:file.lastModified,type:file.type};video.src=state.url;video.hidden=false;$('dropzone').classList.add('has-video');$('dropPrompt').hidden=true;$('sourceName').textContent=file.name;$('videoMeta').textContent='正在读取视频…';video.load();try{await new Promise((resolve,reject)=>{const timer=setTimeout(()=>done(Error('视频读取超时，请尝试更换视频编码')),20000);const done=err=>{clearTimeout(timer);video.removeEventListener('loadeddata',ok);video.removeEventListener('error',bad);err?reject(err):resolve()};const ok=()=>done();const bad=()=>done(Error('浏览器无法解码此视频，请尝试 H.264 MP4'));video.addEventListener('loadeddata',ok,{once:true});video.addEventListener('error',bad,{once:true})});if(seq!==state.loadSeq)return;if(!Number.isFinite(video.duration)||video.duration<=0||!video.videoWidth)throw Error('视频时长或画面无效');state.ready=true;$('timeline').max=video.duration;$('duration').textContent=timeText(video.duration);$('videoMeta').textContent=`${video.videoWidth} × ${video.videoHeight} · ${(file.size/1048576).toFixed(1)} MB`;$('batchStart').value='';$('batchEnd').value='';toast('视频已载入，按 Enter 开始截图')}catch(e){if(seq!==state.loadSeq)return;state.ready=false;video.hidden=true;$('dropzone').classList.remove('has-video');$('dropPrompt').hidden=false;$('videoMeta').textContent='视频读取失败';toast(e.message)}finally{if(seq===state.loadSeq){syncTime();updateControls()}}}
function seek(t){return new Promise((resolve,reject)=>{if(!state.ready)return reject(Error('请先选择视频'));const target=Math.max(0,Math.min(video.duration-0.000001,t));if(Math.abs(video.currentTime-target)<0.00001&&!video.seeking&&video.readyState>=2)return resolve();let timer=setTimeout(()=>done(Error('视频定位超时')),12000);const done=err=>{clearTimeout(timer);video.removeEventListener('seeked',ok);video.removeEventListener('error',bad);err?reject(err):resolve()};const ok=()=>{if(video.readyState>=2)done();else done(Error('视频画面尚未解码'))};const bad=()=>done(Error('视频解码失败'));video.addEventListener('seeked',ok,{once:true});video.addEventListener('error',bad,{once:true});video.currentTime=target})}
async function navigate(t,{pause=false}={}){if(!state.ready||state.busy)return;state.busy=true;if(pause)video.pause();updateControls();try{await seek(t);syncTime()}catch(e){toast(e.message)}finally{state.busy=false;updateControls()}}
function canvasBlob(canvas,type='image/png',quality=1){return new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('图片生成失败，可能内存不足')),type,quality))}
async function takeShot(requestedTime){if(state.shots.length>=200)throw Error('图库已达到 200 张，请导出并清空后继续');if(!state.ready||video.readyState<2||video.seeking)throw Error('请等待视频定位完成再截图');const rate=fps();const c=document.createElement('canvas');c.width=video.videoWidth;c.height=video.videoHeight;const t=video.currentTime;c.getContext('2d').drawImage(video,0,0);const actualRequested=requestedTime===undefined?t:requestedTime;const blob=await canvasBlob(c);const shot={id:state.nextId++,time:t,requestedTime:actualRequested,source:{...state.source},width:c.width,height:c.height,fps:rate,createdAt:new Date().toISOString(),watermark:'inherit',note:'',selected:false,decision:'keep',blob,url:URL.createObjectURL(blob)};state.shots.push(shot);assignShotNumbers(state.shots,$('sort').value);markDirty();return shot}
async function capture(){if(!state.ready||state.busy)return;state.busy=true;if($('pauseAfterCapture').checked)video.pause();updateControls();try{if(video.seeking)await seek(video.currentTime);const shot=await takeShot();$('reviewFilter').value='all';renderGallery();$('gallery').scrollTop=0;toast('已捕获截图 #'+String(shot.number).padStart(3,'0'))}catch(e){toast(e.message)}finally{state.busy=false;updateControls()}}
function shotsForExport(){const a=state.shots.filter(s=>s.selected);return ordered((a.length?a:state.shots).filter(s=>s.decision!=='exclude'))}
function ordered(list){return sortShots(list,$('sort').value)}
function renderGallery(){
 assignShotNumbers(state.shots,$('sort').value);const g=$('gallery');g.replaceChildren();const filter=$('reviewFilter').value;
 const visible=ordered(state.shots).filter(s=>filter==='all'||s.decision===filter);
 if(!visible.length){const d=document.createElement('div');d.className='empty';d.innerHTML=state.shots.length?'<strong>当前筛选下没有截图</strong><p>切换筛选查看其他画面。</p>':'<div class="empty-mark">▧</div><strong>关键画面会留在这里</strong><p>截图后可随时预览、添加说明<br>并单独选择是否带时间戳。</p>';g.append(d)}
 for(const shot of visible){
  const card=document.createElement('article');card.className='card'+(shot.decision==='exclude'?' excluded':'');card.dataset.id=shot.id;
  const thumb=document.createElement('button');thumb.className='thumb';thumb.title='预览截图 #'+String(shot.number).padStart(3,'0');
  const img=document.createElement('img');img.src=shot.url;img.alt='截图 #'+String(shot.number).padStart(3,'0')+' · '+timeText(shot.time);img.loading='lazy';
  const mark=document.createElement('span');mark.className='screen-mark';mark.textContent=stamp(shot.time);mark.hidden=!hasMark(shot);markStyle(mark,settings());mark.style.color=settings().color;
  thumb.append(img,mark);thumb.onclick=()=>openPreview(shot.id);
  const info=document.createElement('div');info.className='card-info';const title=document.createElement('div');title.className='card-title';
  const check=document.createElement('label');check.className='check';const cb=document.createElement('input');cb.type='checkbox';cb.checked=shot.selected;cb.disabled=shot.decision==='exclude';cb.setAttribute('aria-label','选择截图 #'+String(shot.number).padStart(3,'0'));cb.onchange=()=>{shot.selected=cb.checked;updateControls()};check.append(cb,document.createTextNode('#'+String(shot.number).padStart(3,'0')));
  const time=document.createElement('span');time.className='time';time.textContent=timeText(shot.time);title.append(check,time);
  const source=document.createElement('div');source.className='dim';source.textContent=shot.source.name;source.title=shot.source.name;source.style='white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-size:9px;margin-top:4px';
  const note=document.createElement('textarea');note.className='card-note';note.value=shot.note;note.placeholder='画面说明 / 随手笔记…';note.maxLength=2000;note.setAttribute('aria-label','截图 #'+String(shot.number).padStart(3,'0')+' 备注');note.oninput=()=>{shot.note=note.value;markDirty()};
  const select=document.createElement('select');select.setAttribute('aria-label','截图 #'+String(shot.number).padStart(3,'0')+' 水印');for(const [val,text]of [['inherit','水印：跟随全局设置'],['on','水印：带时间戳'],['off','水印：不带时间戳']])select.add(new Option(text,val));select.value=shot.watermark;select.onchange=()=>{shot.watermark=select.value;markDirty();refreshMarks()};
  const actions=document.createElement('div');actions.className='card-footer';const decision=document.createElement('button');decision.className='decision-button'+(shot.decision==='exclude'?' is-excluded':'');decision.textContent=shot.decision==='exclude'?'○ 已排除':'✓ 保留';decision.title=shot.decision==='exclude'?'恢复为保留':'标记排除（不参与图片导出）';decision.onclick=()=>setDecision(shot.id,shot.decision==='exclude'?'keep':'exclude');
  const download=document.createElement('button');download.textContent='↓ 下载';download.disabled=shot.decision==='exclude';download.onclick=()=>downloadShot(shot);
  const del=document.createElement('button');del.className='danger';del.textContent='删除';del.onclick=()=>removeShots([shot.id]);actions.append(decision,download,del);info.append(title,source,note,select,actions);card.append(thumb,info);g.append(card);
 }
 if($('preview').open)syncPreviewNavigation();updateControls();
}
function refreshMarks(){const s=settings();for(const card of $('gallery').querySelectorAll('.card')){const shot=state.shots.find(x=>x.id===Number(card.dataset.id)),mark=card.querySelector('.screen-mark');card.querySelector('select').value=shot.watermark;mark.hidden=!hasMark(shot,s);mark.textContent=stamp(shot.time,s);markStyle(mark,s);mark.style.color=s.color}syncTime();$('screenMark').style.color=s.color}
function removeShots(ids){if(state.busy)return;const removed=state.shots.filter(s=>ids.includes(s.id));if(!removed.length)return;pushUndo({type:'remove',shots:removed});state.shots=state.shots.filter(s=>!ids.includes(s.id));assignShotNumbers(state.shots,$('sort').value);markDirty();renderGallery()}
async function batch(){if(!state.ready||state.busy)return;let times;try{times=currentCapturePlan().times}catch(e){toast(e.message);return}state.busy=true;state.batching=true;state.cancel=false;const wasPlaying=!video.paused;video.pause();const previous=video.currentTime;updateControls();$('batchProgress').hidden=false;$('batchProgress').max=times.length;$('batchProgress').value=0;let done=0;try{for(const t of times){if(state.cancel)break;await seek(t);if(state.cancel)break;await takeShot(t);done++;$('batchProgress').value=done;$('batchStatus').textContent=`正在截帧 ${done} / ${times.length}`;if(done%5===0){$('reviewFilter').value='all';renderGallery()}}$('batchStatus').textContent=(state.cancel?'已停止':'已完成')+` · 捕获 ${done} 张`}catch(e){$('batchStatus').textContent=`中断 · 已捕获 ${done} 张`;toast(e.message)}finally{try{await seek(previous)}catch{}state.busy=false;state.batching=false;if(wasPlaying&&!video.ended){try{await video.play()}catch{toast('浏览器未允许自动续播，请点击播放')}}$('batchProgress').hidden=true;$('reviewFilter').value='all';renderGallery();syncTime();updateControls()}}
async function output(shot,s=settings(),forcePNG=false){const c=document.createElement('canvas');c.width=shot.width;c.height=shot.height;const img=await createImageBitmap(shot.blob);const ctx=c.getContext('2d');ctx.drawImage(img,0,0);img.close();if(hasMark(shot,s)){const text=stamp(shot.time,s,true),size=Math.max(12,Math.round(c.width*s.size)),pad=Math.round(size*.5),margin=Math.round(c.width*.015);ctx.font=`500 ${size}px monospace`;const w=ctx.measureText(text).width+pad*2,h=size+pad*2;const x=s.position[1]==='l'?margin:c.width-w-margin,y=s.position[0]==='t'?margin:c.height-h-margin;ctx.fillStyle='rgba(0,0,0,.70)';ctx.fillRect(x,y,w,h);ctx.fillStyle=s.color||'#fff';ctx.textBaseline='middle';ctx.fillText(text,x+pad,y+h/2)}const blob=await canvasBlob(c,forcePNG?'image/png':'image/'+s.format,s.quality);if(!forcePNG&&blob.type!=='image/'+s.format)throw Error('此浏览器不支持选定图片格式，请改为 PNG 或 JPG');return blob}
function safeName(value){return value.replace(/[<>:"/\\|?*\x00-\x1f]/g,'_').replace(/[. ]+$/,'').slice(0,100)||'视频截图'}
function filename(shot,s=settings()){return `${safeName(s.prefix)}_${String(shot.number).padStart(3,'0')}_${timeText(shot.time).replace(/:/g,'-')}.${s.format==='jpeg'?'jpg':s.format}`}
async function save(blob,name){return WorkbenchHost.save(blob,name)}
async function downloadShot(shot){try{const s=settings();await save(await output(shot,s),filename(shot,s))}catch(e){toast(e.message)}}
async function openPreview(id){const seq=++state.previewSeq;try{const shot=state.shots.find(x=>x.id===id);if(!shot)return;const blob=await output({...shot},settings(),true);if(seq!==state.previewSeq||!state.shots.some(s=>s.id===id))return;state.previewId=id;if(state.previewURL)URL.revokeObjectURL(state.previewURL);state.previewURL=URL.createObjectURL(blob);$('previewImage').src=state.previewURL;$('previewTitle').textContent='截图 #'+String(shot.number).padStart(3,'0');$('previewDetail').textContent=`${shot.source.name} · 视频位置 ${timeText(shot.time)} · ${shot.width} × ${shot.height}`+(shot.note?' · '+shot.note:'');$('previewWatermark').value=shot.watermark;syncPreviewNavigation();if(!$('preview').open)$('preview').showModal()}catch(e){if(seq===state.previewSeq)toast(e.message)}}
function metadata(shots,s){return shots.map(shot=>({id:shot.number,captureId:shot.id,filename:filename(shot,s),caseName:s.caseName,source:shot.source,videoTime:timeText(shot.time),videoTimeSeconds:shot.time,requestedTimeSeconds:shot.requestedTime,width:shot.width,height:shot.height,stepFPS:shot.fps,approximateFrame:Math.floor(shot.time*shot.fps),watermark:hasMark(shot,s),watermarkText:hasMark(shot,s)?stamp(shot.time,s,true):'',watermarkMode:s.mode,recordingStart:s.mode==='clock'?s.start:null,watermarkPosition:s.position,watermarkColor:s.color,decision:shot.decision,note:shot.note,capturedAt:shot.createdAt}))}
function csv(rows){const headers=['编号','图片文件','项目/片段','来源视频','视频位置','视频秒数','宽度','高度','步进帧率','带水印','水印内容','画面备注','来源文件字节数','来源文件修改时间'];const protect=v=>{let t=String(v??'');if(/^[\s]*[=+\-@]/.test(t))t="'"+t;return '"'+t.replace(/"/g,'""')+'"'};return '\ufeff'+[headers,...rows.map(r=>[r.id,r.filename,r.caseName,r.source.name,r.videoTime,r.videoTimeSeconds,r.width,r.height,r.stepFPS,r.watermark?'是':'否',r.watermarkText,r.note,r.source.size,new Date(r.source.lastModified).toISOString()])].map(row=>row.map(protect).join(',')).join('\r\n')}
const crcTable=Array.from({length:256},(_,i)=>{for(let j=0;j<8;j++)i=(i&1)?0xedb88320^(i>>>1):i>>>1;return i>>>0});
function crc32(data){let c=0xffffffff;for(const b of data)c=crcTable[(c^b)&255]^(c>>>8);return (c^0xffffffff)>>>0}
async function zipArchive(files,onProgress){const enc=new TextEncoder(),parts=[],central=[];let offset=0,index=0;const now=new Date(),year=Math.max(1980,Math.min(2107,now.getFullYear())),dt=((year-1980)<<9)|((now.getMonth()+1)<<5)|now.getDate(),tm=(now.getHours()<<11)|(now.getMinutes()<<5)|Math.floor(now.getSeconds()/2);for(const f of files){const name=enc.encode(f.name),data=new Uint8Array(await f.blob.arrayBuffer());if(data.length+offset>0xffffffff)throw Error('ZIP 超过 4GB，请分批导出');const crc=crc32(data),h=new Uint8Array(30),v=new DataView(h.buffer);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x800,true);v.setUint16(10,tm,true);v.setUint16(12,dt,true);v.setUint32(14,crc,true);v.setUint32(18,data.length,true);v.setUint32(22,data.length,true);v.setUint16(26,name.length,true);parts.push(h,name,f.blob);const ch=new Uint8Array(46),cv=new DataView(ch.buffer);cv.setUint32(0,0x02014b50,true);cv.setUint16(4,20,true);cv.setUint16(6,20,true);cv.setUint16(8,0x800,true);cv.setUint16(12,tm,true);cv.setUint16(14,dt,true);cv.setUint32(16,crc,true);cv.setUint32(20,data.length,true);cv.setUint32(24,data.length,true);cv.setUint16(28,name.length,true);cv.setUint32(42,offset,true);central.push(ch,name);offset+=30+name.length+data.length;onProgress?.(++index);await new Promise(r=>setTimeout(r,0))}const centralSize=central.reduce((s,p)=>s+p.length,0),end=new Uint8Array(22),ev=new DataView(end.buffer);ev.setUint32(0,0x06054b50,true);ev.setUint16(8,files.length,true);ev.setUint16(10,files.length,true);ev.setUint32(12,centralSize,true);ev.setUint32(16,offset,true);return new Blob([...parts,...central,end],{type:'application/zip'})}
async function exportZip(){if(state.busy||!state.shots.length)return;state.busy=true;updateControls();const shots=shotsForExport().map(shot=>({...shot,source:{...shot.source}})),s=settings();$('zipBtn').textContent='正在准备…';try{if(!shots.length)throw Error('没有可导出的保留截图');const rows=metadata(shots,s),files=[];for(let i=0;i<shots.length;i++){$('zipBtn').textContent=`生成图片 ${i+1}/${shots.length}`;files.push({name:filename(shots[i],s),blob:await output(shots[i],s)})}files.push({name:'截图清单.csv',blob:new Blob([csv(rows)],{type:'text/csv;charset=utf-8'})},{name:'元数据.json',blob:new Blob([JSON.stringify({tool:'帧记 Frame Notes',version:'1.0.2',exportedAt:new Date().toISOString(),settings:s,timeNotice:'视频内时间为浏览器定位时间；录像日期时间由用户填写起始时间推算；帧号按设定帧率估算。',screenshots:rows},null,2)],{type:'application/json'})});const zip=await zipArchive(files,i=>$('zipBtn').textContent=`打包 ${i}/${files.length}`);const saved=await save(zip,safeName(s.caseName||s.prefix)+'_截图材料.zip');if(saved)toast(`已导出 ${shots.length} 张截图及清单`)}catch(e){toast(e.message)}finally{state.busy=false;$('zipBtn').textContent='↓ 下载 ZIP';updateControls()}}
$('fileInput').onchange=e=>{loadFile(e.target.files[0]);e.target.value=''};for(const id of ['openBtn','pickBtn'])$(id).onclick=()=>$('fileInput').click();$('dropzone').ondragover=e=>{e.preventDefault();if(!state.busy)$('dropzone').classList.add('dragging')};$('dropzone').ondragleave=()=>$('dropzone').classList.remove('dragging');$('dropzone').ondrop=e=>{e.preventDefault();$('dropzone').classList.remove('dragging');loadFile(e.dataTransfer.files[0])};
async function togglePlay(){if(!state.ready||state.busy)return;try{video.paused?await video.play():video.pause()}catch(e){toast('播放失败：'+e.message)}updateControls()}
$('playBtn').onclick=togglePlay;video.onclick=togglePlay;video.onplay=updateControls;video.onpause=updateControls;video.ontimeupdate=queueTimeSync;video.onseeked=queueTimeSync;video.onerror=()=>{if(state.ready){state.ready=false;updateControls();toast('视频解码中断，请重新选择视频')}};$('speed').onchange=()=>video.playbackRate=Number($('speed').value);$('muted').onchange=()=>setPlaybackMuted($('muted').checked);$('showGrid').onchange=()=>$('gridOverlay').hidden=!$('showGrid').checked;
$('timeline').oninput=()=>{state.scrubbing=true;$('now').textContent=timeText(Number($('timeline').value))};$('timeline').onchange=()=>{const target=Number($('timeline').value);state.scrubbing=false;navigate(target)};$('timeline').onblur=()=>{state.scrubbing=false;syncTime()};$('jumpBtn').onclick=()=>{const t=parseTime($('jumpTime').value);if(!Number.isFinite(t)||t>video.duration){toast('请输入视频时长以内的秒数或 HH:MM:SS.mmm');return}navigate(t)};function step(dir){try{navigate(video.currentTime+dir/fps(),{pause:true})}catch(e){toast(e.message)}}$('prevBtn').onclick=()=>step(-1);$('nextBtn').onclick=()=>step(1);$('captureBtn').onclick=capture;$('batchBtn').onclick=batch;$('cancelBtn').onclick=()=>{state.cancel=true;$('batchStatus').textContent='正在停止…'};
$('batchMode').onchange=()=>{const frame=$('batchMode').value==='frame';$('startLabel').textContent=frame?'起始帧（从 0 开始）':'起点（秒或 HH:MM:SS）';$('endLabel').textContent=frame?'终止帧（含）':'终点（秒或 HH:MM:SS）';$('stepLabel').textContent=frame?'间隔（帧）':'间隔（秒）';$('batchStep').value=1;$('batchStep').step=frame?'1':'0.1';$('batchStep').min=frame?'1':'0.001';$('batchStart').value='';$('batchEnd').value='';estimateBatch()};for(const [id,target] of [['setStart','batchStart'],['setEnd','batchEnd']])$(id).onclick=()=>{try{$(target).value=$('batchMode').value==='frame'?Math.floor(video.currentTime*fps()):video.currentTime.toFixed(3);estimateBatch()}catch(e){toast(e.message)}};
for(const id of ['watermark','stampMode','stampPosition','stampSize','recordStart','stampColor'])$(id).addEventListener('input',()=>{$('clockLabel').hidden=$('stampMode').value!=='clock';refreshMarks();markDirty()});$('quality').oninput=()=>$('qualityValue').textContent=$('quality').value+'%';$('format').onchange=()=>{$('formatHint').textContent=$('format').value==='png'?'PNG 无损导出，不受压缩质量设置影响。':'质量越高越清晰，文件也越大。';$('quality').disabled=$('format').value==='png'};$('quality').disabled=true;
$('sort').onchange=()=>{markDirty();renderGallery()};$('reviewFilter').onchange=renderGallery;$('selectAll').onchange=()=>{for(const s of state.shots)s.selected=s.decision!=='exclude'&&$('selectAll').checked;renderGallery()};$('deleteSelected').onclick=()=>removeShots(state.shots.filter(s=>s.selected).map(s=>s.id));$('clearBtn').onclick=()=>{if(!state.busy&&confirm('清空图库中的全部截图？未导出的截图将丢失。'))removeShots(state.shots.map(s=>s.id))};$('zipBtn').onclick=exportZip;$('csvBtn').onclick=async()=>{try{const s=settings();await save(new Blob([csv(metadata(shotsForExport(),s))],{type:'text/csv;charset=utf-8'}),safeName(s.caseName||s.prefix)+'_截图清单.csv')}catch(e){toast(e.message)}};
$('helpBtn').onclick=()=>$('help').showModal();$('closeHelp').onclick=()=>$('help').close();$('closePreview').onclick=()=>$('preview').close();$('preview').onclose=()=>{state.previewSeq++;if(state.previewURL)URL.revokeObjectURL(state.previewURL);state.previewURL=null};$('previewWatermark').onchange=()=>{const shot=state.shots.find(s=>s.id===state.previewId);if(shot){shot.watermark=$('previewWatermark').value;markDirty();refreshMarks();openPreview(shot.id)}};$('previewDownload').onclick=()=>{const shot=state.shots.find(s=>s.id===state.previewId);if(shot)downloadShot(shot)};$('copyBtn').onclick=async()=>{try{if(!navigator.clipboard?.write||typeof ClipboardItem==='undefined')throw Error('当前浏览器环境不支持复制图片，请下载 PNG 后复制');const shot=state.shots.find(s=>s.id===state.previewId);await navigator.clipboard.write([new ClipboardItem({'image/png':await output(shot,settings(),true)})]);toast('图片已复制')}catch(e){toast(e.message)}};
document.addEventListener('keydown',e=>{
 const active=document.activeElement;
 if(e.defaultPrevented||active?.isContentEditable||document.querySelector('dialog[open]')||e.ctrlKey||e.metaKey||e.altKey||state.busy||state.workspace!=='video')return;
 if(['INPUT','TEXTAREA','SELECT'].includes(active?.tagName)&&active.id!=='timeline')return;
 if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();navigate(video.currentTime+(e.key==='ArrowLeft'?-1.5:1.5));return}
 if(['INPUT','BUTTON'].includes(active?.tagName))return;
 if(e.code==='Space'){e.preventDefault();togglePlay()}else if(e.key.toLowerCase()==='m'){e.preventDefault();setPlaybackMuted(!video.muted)}else if(e.key==='Enter'&&state.functionId==='manual'){e.preventDefault();capture()}
});window.addEventListener('beforeunload',e=>{if(state.dirty||state.busy){e.preventDefault();e.returnValue=''}});
